### ISSUE TITLE
API wish, dlg_custom

### ISSUE THREAD

**Issue by Alexey-T** [andreikop/enki#424]
i just suggest this API. API from CudaText.
maybe it helps to Enki.

Its docs is here- function dlg_custom
http://wiki.freepascal.org/CudaText_API#dlg_custom

then Enki can make dialogs.

**Comment by bjones1** [comment]
Given that Enki uses PyQt, I would think the standard dialogs coupled with the ability to create custom dialog in .ui files would be sufficient -- this is already is quite a bit of the Enki plugins codebase.
