### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by bjones1** [andreikop/enki#426]
I've been putting a lot of effort into porting the preview plugin to use QWebEngine. I've now got almost everything working, but I'm seeing a failing in CI that seems unrelated. @andreikop, do you have time to take a look? See [Travis](https://travis-ci.org/bjones1/enki/builds/223413928) and [Appveyor](https://ci.appveyor.com/project/bjones1/enki/build/1.0.43) runs. (This is on my [branch](https://github.com/bjones1/enki/tree/qtwebengine)).

```
======================================================================
FAIL: test_1 (test_plugins.test_lint.Test)
File is checked after opened
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/bjones1/enki/tests/test_lib/../test_plugins/test_lint.py", line 36, in test_1
    self.assertEqual(doc.qutepart.lintMarks, {})
AssertionError: {0: ('e', "F821 undefined name 'asdf'"), 1[37 chars]le')} != {}
+ {}
- {0: ('e', "F821 undefined name 'asdf'"),
-  1: ('w', 'W391 blank line at end of file')}
```

**Comment by andreikop** [comment]
I"ll try later today. But I'm not sure

**Comment by andreikop** [comment]
I've disabled tests which rely on flake8 output.
Such a tests might behave different on different flake8 versions.

**Comment by bjones1** [comment]
Sounds good. Thanks for taking a look!
