### ISSUE TITLE
Grammar error on the homepage: "Where is package for my OS?"

### ISSUE THREAD

**Issue by shlomif** [andreikop/enki#439]
"Where is package for my OS?" on http://enki-editor.org/ is missing a "the". Please correct it.

**Comment by andreikop** [comment]
Thanks!
Fixed

**Comment by shlomif** [comment]
On Mon, 04 Dec 2017 15:40:34 +0000 (UTC)
Andrei Kopats <notifications@github.com> wrote:

> Thanks!
> Fixed
> 

Thanks!

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Escape from GNU Autohell - http://www.shlomifish.org/open-source/anti/autohell/

When Chuck Norris drops a cat, it falls on its back so it won’t lose
eye contact with Chuck.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - http://shlom.in/reply .
