### ISSUE TITLE
Separate test for optional dependencies

### ISSUE THREAD

**Issue by abitrolly** [andreikop/enki#450]
To make sure that Enki still works without optional dependencies, it may be convenient to separate tests for optional things. Right now tests fail without optional `docutils` installed. It is trivial to fix just by installing `docutils` on the test server, but then it is easy to miss the situation when modules like `docutils` become non-optional.

https://travis-ci.org/andreikop/enki/jobs/417026472#L297
https://github.com/andreikop/enki/blob/3c6f030c370321c3b87b1cde459559380941635b/tests/run_all.py#L7

**Comment by bjones1** [comment]
The [import_fail](https://github.com/andreikop/enki/blob/master/tests/test_plugins/import_fail.py) module provides the ability to make installed modules report as not being installed, in order to verify that optional dependencies really are.

**Comment by abitrolly** [comment]
So how to fix Travis? https://travis-ci.org/andreikop/enki/

**Comment by bjones1** [comment]
See https://github.com/andreikop/enki/issues/449#issuecomment-413744509.
