### ISSUE TITLE
Traceback on Ctrl+E is only visible after console entry

### ISSUE THREAD

**Issue by abitrolly** [andreikop/enki#457]
If there is a Traceback while executing current file with Ctrl+E, then Python Interpreter window doesn't show it until another command is entered into the pane below.

![image](https://user-images.githubusercontent.com/8781107/50127585-d2f84200-0282-11e9-9098-5535a506e6d6.png)

![image](https://user-images.githubusercontent.com/8781107/50127595-ddb2d700-0282-11e9-96ca-8c8c58b0e8ac.png)

**Comment by andreikop** [comment]
Which version do you use?
Current version uses Jupyter widget.

**Comment by abitrolly** [comment]
I try to run master with `python3 enki` from checkout directory, but it still shows `Version 17.03.0` in About box. I would say this is a bug in Python 3.6.7 that it is able to find `enki/__main__.py` but doesn't add package into `sys.path`.

**Comment by andreikop** [comment]
I found that Python buffers output by default.
Fixed enki settings to set necessary flags. But haven't done automatic migration. Add `-u` interpreter flag.

**Comment by abitrolly** [comment]
But if exception occurred it should flush out automatically, no?
