### ISSUE TITLE
Alt-I doesn't focus qtconsole to content area

### ISSUE THREAD

**Issue by abitrolly** [andreikop/enki#459]
When I press Alt-I in master, the focus goes to Window, but not to the content area, which requires another unnecessary tab click. It is also unclear how to jump back to source code editing area.

**Comment by andreikop** [comment]
I tried now to reproduce the bug on my laptop with Linux Mint 18 (Ubuntu 16.04) and found that qtconsole throws exception if I try to open .py file. Enki is totally broken.

```
ImportError: 
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7, PyQt5, PySide >= 1.0.3 or PySide2 is available,
    and only one is imported per session.

    Currently-imported Qt library:   'pyqt5'
    PyQt4 installed:                 True
    PyQt5 installed:                 False
    PySide >= 1.0.3 installed:       False
    PySide2 installed:               False
    Tried to load:                   ['pyqt5']
```
and there are no python package.
On newer linux I managed to run enki with python file only after installed qtconsole as a package.
I'm thinking about rolling back to previous widget. It is not so advanced but at least doesn't cause totally broken editor.
@bjones1 what do you think about it?

**Comment by andreikop** [comment]
@abitrolly , and what do you think?

**Comment by abitrolly** [comment]
@andreikop on Fedora 28 running Enki from source works as expected. If there will be switch back, then https://github.com/andreikop/enki/issues/457 needs to be reopened. Perhaps adding a label to all issues related to old console can help out.

If there is a bug in `qtconsole` on Ubuntu 16.04 then it should be reported I think to `qtconsole` or to Ubuntu.

Python console is a common component for many Python editors. At least Spyder IDE is using Qt and if `qtconsole` has potential to fail for it too, then it is a common problem that should be fixed.

**Comment by bjones1** [comment]
@andreikop, I don't maintain Enki anymore, so it's your choice.

**Comment by andreikop** [comment]
I've switched back to own REPL. With 1 atomic commit, so it's easy to roll back if qtconsole import is fixed
