### ISSUE TITLE
enki tests explicitly try to load non-namespaced sip module

### ISSUE THREAD

**Issue by rdieter** [andreikop/enki#464]
Recent upstream sip releases generally only support namespaced sip modules, which is what fedora (sip/PyQt5) packaging is now trying to implement, and drop support for non-namespaced sip module.

In investigations removing this support, one problematic case was enki that includes code in tests currently like:

tests/test_lib/test_future.py:import sip
tests/test_lib/test_future.py:            sip.delete(o)
tests/base.py:import sip
tests/base.py:    sip.delete(timer)
tests/base.py:    sip.delete(qe)

Possible fixes include:
* replacing 'sip' with 'PyQt5.sip'
or
* remove explicit references to sip altogether

See also downstream issue,
https://bugzilla.redhat.com/show_bug.cgi?id=1752766

**Comment by rdieter** [comment]
and upstream reference to the change,
https://www.riverbankcomputing.com/static/Docs/PyQt5/incompatibilities.html#importing-the-sip-module

**Comment by andreikop** [comment]
I do not support the tests now, because there are a lot of hard-to-track infrastructure problems and the tests consume much more time than save.

**Comment by rapgro** [comment]
As tests/base.py is considered, I can't build a new package in Fedora without disabling execution of nearly *all* tests.

**Comment by andreikop** [comment]
@rapgro, just disable the tests. They are not supposed to be run automatically now.
I haven't deleted the tests because sometimes run it manually, but supporting infrastructure for automatic run takes more time than saves because there are many unexpected problems on various platforms.

**Comment by rapgro** [comment]
Please, don't drop the tests. If they've any sense you should keep with them. That's how TDD should work. Maybe we can drop some difficult platforms then and instead?
