### ISSUE TITLE
slow startup

### ISSUE THREAD

**Issue by jimgreen2013** [andreikop/enki#467]
## computer info
* os: fedora29 lxqt
## problem
it took a few minutes to open Enki, here is the profiling output
```bash
[song@miPad ~]$ enki -p




Import PyQt5                  : 0
Import Qutepart               : 45
Construct application         : 46
Catch SIGINT                  : 0
create main window            : 17
create config                 : 4
Create UISettings             : 4
Create FileFilter             : 0
Create Project                : 0
import workspace              : 1
create workspace              : 10
Create Locator                : 1
Search plugins                : 0
  Load appshortcuts           : 1
  Load comment                : 0
  Load cppfileswitch          : 0
  Load detectindent           : 0
  Load editortoolbar          : 2
  Load filebrowser            : 3
  Load fuzzyopen              : 0
  Load helpmenu               : 30
  Load hideall                : 0
  Load lint                   : 1
  Load navigator              : 1
  Load openterm               : 0
  Load pluginmanager          : 129837
  Load preview                : 1
  Load qpartsettings          : 0
  Load recentfiles            : 0
  Load repl                   : 0
  Load restorepos             : 0
  Load searchreplace          : 2
  Load session                : 0
  Load vimtutor               : 0
  Load workspace_actions      : 0
  Load workspace_commands     : 0
Restore session               : 27
Open files                    : 0
Load state                    : 8
Show main window              : 12
Total                         : 130070
QFileSystemWatcher::removePaths: list is empty
QFileSystemWatcher::removePaths: list is empty
```

**Comment by andreikop** [comment]
@jimgreen2013 , thank you for the report. This is really critical problem. Which Enki version is included to LXQT?
CC @rockiger

**Comment by jimgreen2013** [comment]
@andreikop Enki version is:
Version 18.08.0
 Qutepart 3.2.0 (with binary parser)
 Qt 5.13.2

**Comment by andreikop** [comment]
@rockiger , the problem reproduces on the current version (no fixes to this functionality after).
Could you check it?

**Comment by andreikop** [comment]
I temporary (I hope) removed the slow plugin.
It would be cool if @rockiger migrated the plugin to asyncio to make it non-blocking.
Release 20.03.0 is tagged.
I'm not sure it is possible to update Fedora 29 packages according to policies, but I hope @rapgro will update Fedora package at least for the new releases.

**Comment by rockiger** [comment]
Sorry to hear that. Unfortunately I don't use enki anymore and I don't have much time right now.

**Comment by rapgro** [comment]
Fedora packager here.

> os: fedora29 lxqt

Fedora 29 has reached End Of Life (EOL) and won't get any support any more.
Version 20.03.1 is built in Fedora Rawhide. Please let me know if you need it as update also in the other branches (F32, F31, F30).

**Comment by andreikop** [comment]
Thank you @rapgro

**Comment by dglent** [comment]
I installed Mageia 8 and this release provides Enki 20.03.1 and i discovered that the plugins are disabled !
I was very disappointed as this breaks my habits in programming.
I have no any problem with slowness of opening Enki with the plugins, it opens very fast
So i packaged locally the 19.10.0 with Qt 5.15.2 and python 3.8.9 and **there is no any problem**.

I think that the plugins should stay active
Enki is the only IDE that i found comfortable and fit my needs

**Comment by dglent** [comment]
[dglent@localhost ~]$ enki -p
New document couldn't be found
None is not in list
Import PyQt5                  : 0
Import Qutepart               : 72
Construct application         : 123
Catch SIGINT                  : 2
create main window            : 24
create config                 : 23
Create UISettings             : 8
Create FileFilter             : 0
Create Project                : 0
import workspace              : 1
create workspace              : 15
Create Locator                : 1
Search plugins                : 3
  Load appshortcuts           : 1
  Load comment                : 0
  Load cppfileswitch          : 0
  Load detectindent           : 0
  Load editortoolbar          : 3
  Load filebrowser            : 4
  Load fuzzyopen              : 0
  Load helpmenu               : 91
  Load hideall                : 0
  Load lint                   : 1
  Load navigator              : 3
  Load openterm               : 0
  Load pluginmanager          : 263
  Load preview                : 268
  Load qpartsettings          : 0
  Load recentfiles            : 0
  Load repl                   : 0
  Load restorepos             : 1
  Load searchreplace          : 3
  Load session                : 0
  Load vimtutor               : 0
  Load workspace_actions      : 0
  Load workspace_commands     : 2
Restore session               : 619
Open files                    : 0                                                     
Load state                    : 32                                                    
Show main window              : 121
Total                         : 1701

**Comment by andreikop** [comment]
@dglent , which plugins are missing?

**Comment by dglent** [comment]
I have these plugins installed and enabled:
- Autosave
- Bracket matcher
- Fileswitcher

**Comment by andreikop** [comment]
This is the list of plugins which shall be available in 20.03.1: [the list](https://github.com/andreikop/enki/tree/v20.03.1/enki/plugins)
If something is missing, check the contents of a package and what files are available in `enki` package on file system (`/usr/lib/pythonx.x/site-packages/enki`)

**Comment by dglent** [comment]
I have exactly the same files and folders in my system "/usr/lib/python3.8/site-packages/enki/plugins"
![εικόνα](https://user-images.githubusercontent.com/4337756/120348117-29e01d80-c2fd-11eb-8243-d93a53c06cb0.png)

**Comment by andreikop** [comment]
And what is output of `enki -p` ?

**Comment by dglent** [comment]
[dglent@localhost ~]$ enki -p
New document couldn't be found
None is not in list
Import PyQt5                  : 0
Import Qutepart               : 72
Construct application         : 161
Catch SIGINT                  : 2
create main window            : 24
create config                 : 21
Create UISettings             : 8
Create FileFilter             : 0
Create Project                : 0
import workspace              : 1
create workspace              : 15
Create Locator                : 1
Search plugins                : 3
  Load appshortcuts           : 1
  Load comment                : 0
  Load cppfileswitch          : 0
  Load detectindent           : 0
  Load editortoolbar          : 2
  Load filebrowser            : 4
  Load fuzzyopen              : 0
  Load helpmenu               : 92
  Load hideall                : 0
  Load lint                   : 1
  Load navigator              : 3
  Load openterm               : 0
  Load pluginmanager          : 221
  Load preview                : 267
  Load qpartsettings          : 0
  Load recentfiles            : 0
  Load repl                   : 0
  Load restorepos             : 1
  Load searchreplace          : 3
  Load session                : 0
  Load vimtutor               : 0
  Load workspace_actions      : 0
  Load workspace_commands     : 16
Restore session               : 841
Open files                    : 0                                                     
Load state                    : 19                                                    
Show main window              : 95
Total                         : 1892

**Comment by dglent** [comment]
I have downgraded to  :
Version 19.10.0 (to have the plugins)
Qutepart 3.3.1 (with binary parser)
Qt 5.15.2
