### ISSUE TITLE
python 3.10 enforces explicit float-to-int casting

### ISSUE THREAD

**Issue by rapgro** [andreikop/enki#473]
https://github.com/andreikop/enki/blob/aafee43a1d4c9d8f4e15055b1e13a20578d990ce/enki/widgets/dockwidget.py#L46

No idea but multiplication gives a float when compiled with python 3.10

Please use instead a workaround as in
`self.setIconSize(QSize(int(textHeight * 0.8), int(textHeight * 0.8)))`

**Comment by andreikop** [comment]
Will look soon

**Comment by andreikop** [comment]
Hi

I've fixed the bug and released a version
Checkout master

Btw, @rapgro, I've migrated from Mint to Fedora 35 and it is amazing!

**Comment by rapgro** [comment]
> Btw, @rapgro, I've migrated from Mint to Fedora 35 and it is amazing!

@andreikop  Thanks for the fixes here and in https://github.com/andreikop/qutepart/issues/91. I'm happy to can help with my packages. Are you maybe interested to become co-maintainer of Fedora packages?
