### ISSUE TITLE
Enki crashes after install.

### ISSUE THREAD

**Issue by agoodfellow123** [andreikop/enki#474]
Hello there, I installed enki-editor-git to my arch system via AUR and tried to run it. It gave me this message repeatedly for at least fifteen times:
```
Traceback (most recent call last):

File "/usr/lib/python3.10/site-packages/qutepart/margins.py", line 78, in __updateRequest

self.update(0, rect.y(), self.width(), rect.height() + blockHeight)

TypeError: arguments did not match any overloaded call:

update(self): too many arguments

update(self, QRect): argument 1 has unexpected type 'int'

update(self, QRegion): argument 1 has unexpected type 'int'

update(self, int, int, int, int): argument 4 has unexpected type 'float'
```
I checked all the messages and they were all same. So far I tried to install enki on two computers, one arch one manjaro sadly both gave the same error. I also tried the non git version of the enki-editor on AUR. That gave a different error but crashed like the git version as well.

**Comment by dglent** [comment]
There is this fix in qutepart for python 3.10:
https://github.com/andreikop/qutepart/commit/3dc01dc03aef194da0115c240ff84b629b4c0aa4

**Comment by agoodfellow123** [comment]
Thank you, I changed that file and that problem is solved however now when I try to open settings it gives me this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/enki/core/uisettings.py", line 417, in _onEditSettings
    dialog = UISettings(core.mainWindow())
  File "/usr/lib/python3.10/site-packages/enki/core/uisettings.py", line 315, in __init__
    self.resize(max(hint.width(), hint.height() * 1.61), hint.height())
TypeError: arguments did not match any overloaded call:
  resize(self, QSize): argument 1 has unexpected type 'float'
  resize(self, int, int): argument 1 has unexpected type 'float'
```
I checked out line 417 and 315 at uisettings however the lines seem to be identical with the git version. Also I informed AUR maintainers about the outdated qutepart version.

**Comment by andreikop** [comment]
@agoodfellow123 , thanks for the report and for AUR update. I'll try to fix the bug tomorrow morning.

**Comment by agoodfellow123** [comment]
You are wellcome! And thank you for maintaining.

**Comment by andreikop** [comment]
@agoodfellow123, fixed this. But I will not be surprised if there are some similar mistakes in other places.
